### ISSUE TITLE
Any way for native tooltip to overflow chart container? 

### ISSUE THREAD

**Issue by rwhitten577** [N1ghtly/react-native-responsive-linechart#37]
Hi there, thanks for this library. Works great for me so far, but I'm having trouble getting the tooltips at the end of the x or y axis to overflow and they are getting cut off. Is there any way to do this with the native Tooltip component? Thanks! 

![IMG_442D4D9589E4-1](https://user-images.githubusercontent.com/19270062/100381181-66e1f500-2fe6-11eb-85f8-f71ce8dbb060.jpeg)

**Comment by N1ghtly** [comment]
Hi, unfortunately SVG does not allow overflow outside of the parent container. I'll have to think about some clever way to move the tooltip component out of the chart svg. I'll look into it this week!

**Comment by N1ghtly** [comment]
I've fixed it so it works as long as you don't define a custom viewBox (scrolling chart actually takes advantage of this non overflow property, so tooltips will still be cut off there). Check out v5.3.0 👍

**Comment by rwhitten577** [comment]
Awesome, thanks for your help!

**Comment by flavordaaave** [comment]
@N1ghtly any chance the `scatter` could overflow as well? I have a round `scatter` for selection only which is currently cut of with the chart:

<img width="388" alt="Bildschirmfoto 2020-12-20 um 10 46 17" src="https://user-images.githubusercontent.com/5305150/102710166-c6af8100-42b0-11eb-8de7-2af98945e464.png">

**Comment by N1ghtly** [comment]
@flavordaaave ah yes, good catch, I will fix that tomorrow.

**Comment by N1ghtly** [comment]
@flavordaaave Fixed in v5.3.2

**Comment by DarshanNDK** [comment]
Having the same issue, it's still not working for me on android.
Am I missing something?

![Screenshot_1614672539](https://user-images.githubusercontent.com/61319469/109618053-1d60f300-7b5d-11eb-9ba4-771825c7d821.png)
![Screenshot_1614672641](https://user-images.githubusercontent.com/61319469/109618059-1f2ab680-7b5d-11eb-9bbd-d07f233ba50b.png)
![Screenshot_1614672645](https://user-images.githubusercontent.com/61319469/109618061-1fc34d00-7b5d-11eb-89b0-73688a1e1731.png)
![Screenshot_1614672537](https://user-images.githubusercontent.com/61319469/109618063-205be380-7b5d-11eb-9876-e8502281903f.png)

**Comment by N1ghtly** [comment]
You have to supply enough padding for the tooltip to overflow "into" (on <Chart /> component)

**Comment by DarshanNDK** [comment]
@N1ghtly , thanks for the reply.

Okay, so if there is a long tooltip text then I will have to give it a lot of padding?

and if I do give a big padding, it will result in smaller chart, no?

**Comment by N1ghtly** [comment]
That's correct.

**Comment by DarshanNDK** [comment]
Okay, understood,

do you think that it is possible to implement some positioning logic for library (using dx,dy & position prop)?

if so, I will try and have a PR ready.

**Comment by N1ghtly** [comment]
Definitely possible, the supplied Tooltip component is quite simple & "dumb" at the moment haha :)

**Comment by DarshanNDK** [comment]
Haha, nice one,
I'll see what I can do,

Thank you so much :)

**Comment by faizantariq1** [comment]
HI @rwhitten577  how did you apply dates on the scrollable chart?

**Comment by rwhitten577** [comment]
@faizantariq1 convert your data values to a Unix timestamp, then use the label `formatter` function to convert it back to a date string in the format you want, e.g. `formatter: (v: number) => moment(v).format("MMM DD")`

https://react-native-responsive-linechart.surge.sh/docs/horizontalaxis#horizontalaxis-default-theme

**Comment by faizantariq1** [comment]
@rwhitten577 thankx, i'm doing the same. but want to use the infinite scroll so using the view port with width(which is not adjusting correctly), so when i removed the viewport it's working fine. giving a very short value in viewport
